In [7]:
a = 6
b = 1
c = 8

In [9]:
if a< b:
    print("A is less than b")
elif b> c:
    print("B is greater than c")

In [6]:
print(c)

8


In [8]:
b

1

# `*SMIT CLASS*`
***
***AI and datascience class***<br>
<a href = 'https://www.youtube.com'>youtube.com</a><br>
[aaaaa](https://www.google.com/)
![alt text](image.jpg)
<img src = ''>

> SMIT


1. AI
2. DS
3. DA

- SMIT
    - AIDS
    - GD
    - UIUX
    - WAM

In [1]:
import numpy as np

In [34]:
# my_array = np.ndarray?
my_array1 = np.arange?
my_array1

list_1 = [1, 2, 3, 4, 5]
list_1 = np.array(list_1, dtype = np.float64)
list_1

array([1., 2., 3., 4., 5.])

Docstring:
arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.

In [22]:
my_multi_array = np.array([[1,3,4],['a','b','c'],[True,False,True]]) 
print(my_multi_array[1][1])

b


In [24]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [29]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.ones((5,5)).size

25

In [39]:
myarray = np.arange(1,100)
myarray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [40]:
myarray.size

99

In [44]:
myarray.dtype

dtype('int64')

In [51]:
np.random.randint(1,1000,size= 50)

array([252, 591, 213, 161, 357, 505, 738, 533, 509, 784,  47, 971, 180,
       797, 606, 506, 887, 916, 741, 286, 494, 799,  96, 832, 650, 769,
       543, 351, 549, 111, 978, 140, 673, 747, 677, 628, 914, 838, 926,
       923, 274, 140, 313, 510, 916, 251, 998, 626, 773, 421], dtype=int32)

In [58]:
print(np.random.choice(['H','T'], size = 10000))

['H' 'T' 'T' ... 'H' 'H' 'H']


In [61]:
print("Row: ",np.ones((5,10)).shape[0])
print("column: ",np.ones((5,10)).shape[1])

Row:  5
column:  10


In [5]:
list = [[1,4,5],[6,10,9],[2,8,0]]
myarr1 = np.array(list)
myarr1

array([[ 1,  4,  5],
       [ 6, 10,  9],
       [ 2,  8,  0]])

In [4]:
myarr1.shape

(3, 3)

In [7]:
myarr1[1][1]

np.int64(10)

In [17]:
np.array([1,4,6,7,8,3,6,9])[3:8]

array([7, 8, 3, 6, 9])

In [16]:
myarr1[:2,1:]

array([[ 4,  5],
       [10,  9]])

In [24]:
# myarr1[1,1] = 11
# myarr1.itemset((1,1),11) removed from numpy 2.0

myarr1.item(1,2)


9

In [27]:
myarr2 = np.array([1,4,6,7,8,3,6,9])
np.take(myarr2, [0,3, 5])
# np.put(myarr2,[0,3, 5],[0,0,0])
myarr2

array([1, 4, 6, 7, 8, 3, 6, 9])

In [33]:
myarr2[::2]

array([1, 6, 8, 6])

In [43]:
myarr2[(myarr2%2 == 0) & (myarr2 >5)]

array([[ 1,  4,  5],
       [ 6, 11,  9],
       [ 2,  8,  0]])

In [72]:
gender_data1 = np.random.choice(['M','F'],size = 500)

In [46]:
np.unique(gender_data)

array(['F', 'M'], dtype='<U1')

array(['M', 'M', 'M', 'M', 'F', 'F', 'M', 'F', 'M', 'M', 'F', 'M', 'F',
       'F', 'M', 'F', 'M', 'M', 'F', 'F', 'M', 'F', 'F', 'M', 'M', 'F',
       'F', 'F', 'F', 'M', 'F', 'F', 'M', 'M', 'F', 'M', 'F', 'M', 'M',
       'F', 'F', 'F', 'M', 'F', 'M', 'M', 'F', 'F', 'F', 'F', 'F', 'M',
       'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'F', 'M', 'M', 'F',
       'M', 'M', 'F', 'F', 'F', 'F', 'M', 'F', 'F', 'M', 'F', 'F', 'F',
       'M', 'F', 'F', 'M', 'F', 'M', 'M', 'F', 'M', 'M', 'M', 'F', 'F',
       'F', 'M', 'F', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'F', 'F', 'F',
       'M', 'M', 'F', 'F', 'M', 'M', 'M', 'M', 'F', 'M', 'M', 'F', 'F',
       'F', 'F', 'F', 'F', 'M', 'F', 'F', 'M', 'M', 'F', 'F', 'F', 'F',
       'M', 'M', 'M', 'F', 'M', 'M', 'F', 'F', 'F', 'M', 'F', 'M', 'F',
       'M', 'M', 'F', 'F', 'M', 'F', 'F', 'M', 'F', 'M', 'M', 'F', 'F',
       'M', 'M', 'M', 'M', 'M', 'F', 'M', 'M', 'F', 'F', 'M', 'F', 'M',
       'M', 'F', 'F', 'M', 'M', 'F', 'F', 'M', 'M', 'M', 'M', 'F

In [73]:
# gender_data.reshape((10,10,5))
print(gender_data1)
gender_data1.resize((10,10,10))
gender_data1

['M' 'F' 'M' 'M' 'F' 'M' 'M' 'M' 'M' 'F' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'F' 'M' 'F' 'M' 'F' 'M' 'M' 'M' 'M' 'F' 'M' 'M' 'F' 'M' 'F' 'F' 'M' 'F'
 'M' 'F' 'F' 'F' 'M' 'F' 'F' 'F' 'M' 'F' 'F' 'M' 'F' 'M' 'F' 'M' 'M' 'F'
 'F' 'M' 'M' 'F' 'M' 'M' 'M' 'M' 'M' 'F' 'F' 'F' 'M' 'M' 'F' 'F' 'F' 'F'
 'M' 'M' 'M' 'F' 'M' 'M' 'F' 'F' 'M' 'M' 'F' 'F' 'F' 'F' 'M' 'F' 'F' 'M'
 'M' 'M' 'F' 'M' 'F' 'M' 'M' 'M' 'M' 'F' 'M' 'M' 'M' 'F' 'M' 'M' 'M' 'F'
 'F' 'M' 'F' 'F' 'F' 'F' 'F' 'F' 'F' 'M' 'F' 'M' 'M' 'F' 'F' 'F' 'M' 'M'
 'M' 'M' 'F' 'F' 'M' 'M' 'M' 'M' 'F' 'F' 'F' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'F' 'F' 'F' 'M' 'M' 'M' 'M' 'F' 'M' 'F' 'F' 'M' 'M'
 'M' 'M' 'M' 'M' 'F' 'F' 'F' 'F' 'F' 'F' 'F' 'M' 'M' 'M' 'M' 'M' 'F' 'F'
 'F' 'M' 'F' 'M' 'F' 'F' 'M' 'M' 'F' 'M' 'M' 'M' 'F' 'F' 'M' 'M' 'M' 'M'
 'F' 'F' 'M' 'M' 'F' 'M' 'F' 'F' 'M' 'M' 'M' 'M' 'F' 'F' 'F' 'F' 'F' 'M'
 'F' 'F' 'F' 'F' 'M' 'M' 'M' 'M' 'M' 'M' 'F' 'M' 'F' 'M' 'F' 'F' 'M' 'M'
 'F' 'M' 'F' 'F' 'F' 'M' 'F' 'M' 'F' 'F' 'M' 'F' 'M

array([[['M', 'F', 'M', 'M', 'F', 'M', 'M', 'M', 'M', 'F'],
        ['M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'F', 'M'],
        ['F', 'M', 'F', 'M', 'M', 'M', 'M', 'F', 'M', 'M'],
        ['F', 'M', 'F', 'F', 'M', 'F', 'M', 'F', 'F', 'F'],
        ['M', 'F', 'F', 'F', 'M', 'F', 'F', 'M', 'F', 'M'],
        ['F', 'M', 'M', 'F', 'F', 'M', 'M', 'F', 'M', 'M'],
        ['M', 'M', 'M', 'F', 'F', 'F', 'M', 'M', 'F', 'F'],
        ['F', 'F', 'M', 'M', 'M', 'F', 'M', 'M', 'F', 'F'],
        ['M', 'M', 'F', 'F', 'F', 'F', 'M', 'F', 'F', 'M'],
        ['M', 'M', 'F', 'M', 'F', 'M', 'M', 'M', 'M', 'F']],

       [['M', 'M', 'M', 'F', 'M', 'M', 'M', 'F', 'F', 'M'],
        ['F', 'F', 'F', 'F', 'F', 'F', 'F', 'M', 'F', 'M'],
        ['M', 'F', 'F', 'F', 'M', 'M', 'M', 'M', 'F', 'F'],
        ['M', 'M', 'M', 'M', 'F', 'F', 'F', 'M', 'M', 'M'],
        ['M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'F'],
        ['F', 'F', 'M', 'M', 'M', 'M', 'F', 'M', 'F', 'F'],
        ['M', 'M', 'M', 'M', 'M', 'M',

In [110]:
myarr3 = np.random.randint(1,10, size = (3,3))

In [77]:
myarr3

array([[4, 8, 3],
       [1, 4, 5],
       [2, 1, 3]], dtype=int32)

In [87]:
myarr3.transpose((1,0))

array([[4, 1, 2],
       [8, 4, 1],
       [3, 5, 3]], dtype=int32)

In [92]:
myarr3.swapaxes(0,1)

array([[4, 1, 2],
       [8, 4, 1],
       [3, 5, 3]], dtype=int32)

In [99]:
myarr3.flatten(order = 'C')


array([4, 8, 3, 1, 4, 5, 2, 1, 3], dtype=int32)

In [113]:
myarr3.sort(axis= 1)

In [114]:
myarr3

array([[2, 3, 5],
       [5, 7, 9],
       [9, 9, 9]], dtype=int32)

In [129]:
my_new_aa_1 = np.arange(1,10).reshape((3,3))
my_new_aa_2 = np.arange(11,20).reshape((3,3))
print(my_new_aa_1)
print("_____________\n")
print(my_new_aa_2)

np.vstack((my_new_aa_1,my_new_aa_2))

np.hstack((my_new_aa_1,my_new_aa_2))
np.row_stack((my_new_aa_1,my_new_aa_2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
_____________

[[11 12 13]
 [14 15 16]
 [17 18 19]]


C:\Users\memon\AppData\Local\Temp\ipykernel_29008\3639057441.py:10: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((my_new_aa_1,my_new_aa_2))


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [157]:
ss_arr_5 = np.random.randint(10, size=(2, 20))
print(ss_arr_5)
np.hsplit(ss_arr_5, (4,8,12,16))

[[6 0 4 4 9 2 7 1 6 8 8 9 7 6 3 8 3 1 1 6]
 [3 5 0 9 9 5 5 8 5 8 5 1 7 1 7 0 6 4 7 9]]


[array([[6, 0, 4, 4],
        [3, 5, 0, 9]], dtype=int32),
 array([[9, 2, 7, 1],
        [9, 5, 5, 8]], dtype=int32),
 array([[6, 8, 8, 9],
        [5, 8, 5, 1]], dtype=int32),
 array([[7, 6, 3, 8],
        [7, 1, 7, 0]], dtype=int32),
 array([[3, 1, 1, 6],
        [6, 4, 7, 9]], dtype=int32)]

In [156]:
ss_arr_6 = np.random.randint(10, size=(10, 2))
print(ss_arr_6)
np.vsplit(ss_arr_6, (2,4,6,8))

[[1 2]
 [8 6]
 [5 0]
 [7 8]
 [7 3]
 [9 3]
 [8 2]
 [7 7]
 [6 9]
 [4 7]]


[array([[1, 2],
        [8, 6]], dtype=int32),
 array([[5, 0],
        [7, 8]], dtype=int32),
 array([[7, 3],
        [9, 3]], dtype=int32),
 array([[8, 2],
        [7, 7]], dtype=int32),
 array([[6, 9],
        [4, 7]], dtype=int32)]

# Copying

In [24]:
my_arr2 = np.random.randint(100,size = (3,3))
my_arr2

array([[43,  7, 90],
       [46, 82, 28],
       [42, 56, 19]], dtype=int32)

In [25]:
# copy_my_arr2 = my_arr2

# copy_my_arr2.sort()
# print(copy_my_arr2)
# print(my_arr2)
view_my_arr2 = my_arr2.view()
copy_my_arr2 = my_arr2.copy()
copy_my_arr2.sort()


# view_my_arr2.sort()
# print(view_my_arr2)
print(copy_my_arr2)
print(my_arr2)
# view_my_arr2

[[ 7 43 90]
 [28 46 82]
 [19 42 56]]
[[43  7 90]
 [46 82 28]
 [42 56 19]]


# Math

In [68]:
list1 = np.array([[1,5,3],[7,8,0],[3,3,5]])
list2 = np.array([[3,7,6],[6,9,6],[8,6,7]])
print(list2)
list3 = list1 + list2
list3
list3 = list1 - list2
list3
list3 = list1 * list2
list3
list3 = list1 / list2
list3
list3 = list1 % list2
list3
list1.sum()
# print(list2.sum())
# print(list2.cumsum())
print(list2.min())
print(list2.max())
print(list2.argmax())


np.add(list1, list2)
my_arr2_square = np.power(list2,2)
print(np.sqrt(my_arr2_square).astype(int))
np.absolute(np.arange(-10,-1))
np.gcd.reduce([9, 12, 15])
np.lcm.reduce([9, 12, 15])
# Round down
np.floor([1.2, 2.7])
# Round up
np.ceil([1.2, 2.5])
list2**2

[[3 7 6]
 [6 9 6]
 [8 6 7]]
3
9
4
[[3 7 6]
 [6 9 6]
 [8 6 7]]


array([[ 9, 49, 36],
       [36, 81, 36],
       [64, 36, 49]])

In [81]:
print(list2)
argmaxlist2 = list2.argmax(axis = 1)
print(argmaxlist2)
list2[:,argmaxlist2]

[[3 7 6]
 [6 9 6]
 [8 6 7]]
[1 1 0]


array([[7, 7, 3],
       [9, 9, 6],
       [6, 6, 8]])

In [107]:
studentdata = [["Math","Scince","English","Urdu","Sindhi"],
               [50,60,70,80,40],
               [30,70,80,40,60],
               [20,40,60,80,90],
               [30,60,80,50,40],
               [40,40,30,60,80]]
subjects = studentdata.pop(0)
studentdata = np.array(studentdata)
max_subject = studentdata.argmax(axis = 0)
print(max_subject)
max_student = studentdata.argmax(axis = 1)
print(max_student)

for i in range(0, len(subjects)):
    maxVal = max_subject[i]
    print(f"{subjects[i]}: max marks: {studentdata[maxVal,i]}")
for loc, student in enumerate(studentdata):
    maxVal = max_student[loc]
    print(f"Student no: {loc+1}\nMax Marks: {studentdata[loc, maxVal]} in subject: {subjects[maxVal]}")
    print("__________________")
    
    

[0 1 1 0 2]
[3 2 4 2 4]
Math: max marks: 50
Scince: max marks: 70
English: max marks: 80
Urdu: max marks: 80
Sindhi: max marks: 90
Student no: 1
Max Marks: 80 in subject: Urdu
__________________
Student no: 2
Max Marks: 80 in subject: English
__________________
Student no: 3
Max Marks: 90 in subject: Sindhi
__________________
Student no: 4
Max Marks: 80 in subject: English
__________________
Student no: 5
Max Marks: 80 in subject: Sindhi
__________________


In [108]:
Student_data = {"st-1":{"Maths":85,"Urdu":70,"Sindhi":40,"Chemistry":90,"Physics":60},
               "st-2":{"Maths":70,"Urdu":75,"Sindhi":40,"Chemistry":90,"Physics":60},
               "st-3":{"Maths":80,"Urdu":70,"Sindhi":95,"Chemistry":90,"Physics":60},
               "st-4":{"Maths":80,"Urdu":70,"Sindhi":50,"Chemistry":85,"Physics":60},
               "st-5":{"Maths":80,"Urdu":75,"Sindhi":40,"Chemistry":90,"Physics":60}}

In [122]:
data = [50,60,70,80,40]
data = np.array(data)
data.argsort()[::-1]


array([3, 2, 1, 0, 4])