# Finding Outliers Using central tandancy
## 1. Mean

## 2. Median

## 3. Mode


# Linear Algabra
### To use linear algabra in numpy import 
### from numpy import linalg as LA
## 1. Dot Product
## 2. Multi Dot
## 3. Inverse Matrix
## 4. Determinant
## 5. Inner product
## 6. Matrix Power


In [20]:
import numpy as np
my_arr1 = np.array ([[1,2],[3,4]])
my_arr2 = np.array([[2,4],[6,9]])
print(f"my_arr1:\n{my_arr1}")
print(f"my_arr2:\n{my_arr2}")

print(np.linalg.multi_dot([my_arr1,my_arr2]))
# [1,2][2,6] = arr1[0][:]arr2[:][0]
# (1x2)+(2x6) = 14
# [1,2][4,9] = arr1[0][:]arr2[:][1]
# (1x4)+(2x9) = 22
# [3,4][2,6] = arr1[1][:]arr2[:][0]
# (3x2)+(4x6) = 30
# [3,4][4,9] = arr1[1][:]arr2[:][1]
# (3x4)+(4x9) = 48

np.linalg.multi_dot([my_arr1,my_arr2,[1,2]])
# my_arr1.my_arr2
# [[14, 22],
#  [30, 48]]
# [14,22][1,2] = (14x1)+(22x2) = 58
# [30,48][1,2] = (30x1)+(48x2) = 126


np.linalg.det(my_arr1)

np.linalg.inv(my_arr2)

np.inner(my_arr1, my_arr2)
# [1,2][2,4] 
# (1 x 2) + (2 x 4) = 10 [0,0]
# [1,2][6,9]
# (1 x 6) + (2 x 9) = 24 [0,1]
# [3,4][2,4]
# (3 x 2) + (4 x 4) = 22 [1,0]
# [3,4][6,9]
# (3 x 6) + (4 x 9) = 54 [1,1]

np.pow(my_arr1, 2)

my_arr1:
[[1 2]
 [3 4]]
my_arr2:
[[2 4]
 [6 9]]
[[14 22]
 [30 48]]


array([[ 1,  4],
       [ 9, 16]])

## Airthmatic Mean
## Geometric Mean

In [ ]:
mylist = [2,4,8,16,32,64,128,256]

in my business the initial investment was 2500$, for last 5 years i have a profit of [25%,30%,-10%,100%,-20%] i need know how much money i have in my account and is my company profitable or not

In [67]:
profit = np.array([0.25,0.30,-0.10,1,-0.20])
profit_dol = profit*2500
total_amount = 2500
for profit_p_year in profit:
    total_amount += total_amount * profit_p_year
print(total_amount)

5850.0


In [48]:
year1 = 2500+ 2500*0.25
year2 = year1+ year1*0.30
year3 = year2+ year2*-0.10
year4 = year3+ year3*1
year5 = year4+ year4*-0.20
print(year5)

5850.0


In [40]:
profit.sum()/len(profit)

np.float64(33.0)

In [49]:
np.pow(profit.prod(),1/len(profit))

np.float64(0.2724069927426661)

In [51]:
(2500+(2500*0.2724)*5)

5905.0

In [47]:
2500+(2500*0.25)*5

5625.0

In [66]:
profit
factor = profit + 1
print(factor)
product_of_factor = factor.prod()
print(product_of_factor)
amount = 2500*product_of_factor
amount


[0.9 1.2 1.8 0.7 0.6 0.8 1.3 1.6 0.9 1.2]
1.4673125376


np.float64(3668.281344)

## 9000 is initial investment and the rcord of last ten years is [-10%,20%,80%,-30%,-40%,-20%,30%,60%,-10%,20%] and find average profit or loss per year

In [84]:
initial = 9000
profit = np.array([-10,20,80,-30,-40,-20,30,60,-10,20])
profit = profit/100
print(1/len(profit))
factors = profit + 1
gmean = np.pow(factor.prod(), 1/len(factors))-1
total_amount = initial*factor.prod()
print(f"Total amount: {total_amount}")
print(f"Amean: {profit.mean(): .2f}")
print(f"Gmean: {gmean}")

0.1
Total amount: 13205.812838400001
Amean:  0.10
Gmean: 0.039087840845481114


In [70]:
factors = profit + 1
total_amount = initial*factor.prod()
print(f"Total amount: {total_amount}")


Total amount: 13205.812838400001


In [88]:
(initial+(9000*0.1)*10)

18000.0